### ISSUE TITLE
GCC version 6 is not enough to build Atomspace, at least 7 or later is required

### ISSUE THREAD

**Issue by vsbogd** [opencog/cogutil#239]
Cogutil macro checks that GCC is 6 or later:
https://github.com/opencog/cogutil/blob/d1f3df098824e14ed8e1a74933e7aeab2ea022fb/cmake/OpenCogGccOptions.cmake#L5-L9
but `std::set::merge` method which is used in `atomspace` code: 
https://github.com/opencog/atomspace/blob/a633fe2b66cbd9c83cb2d71517a19cc924758703/opencog/atoms/container/JoinLink.cc#L139
was introduced in GCC starting from version 7.

**Comment by ngeiswei** [comment]
I have personally no problem incrementing the required version of gcc. Note that Debian 9 still uses gcc 6.

**Comment by linas** [comment]
This implies that Debian 9 won't compile opencog ...

**Comment by linas** [comment]
Pull req #245 bumps version to 7.0

**Comment by linas** [comment]
Closing; fixed in #245  I set it to 7.0 but I think its safe to go to 7.5 even, as ubuntu 18.04 LTS has 7.5 in it.  Open a new bug if you want something else.
