### ISSUE TITLE
instructions are wrong

### ISSUE THREAD

**Issue by sjatkins** [opencog/cogutil#86]
cd to project root dir
    mkdir build
    cd build
    cmake ..
    make

When I mkdir build && cd build the cmake .. doesn't put anything into the build diretory.  At the end it says
-- Build files have been written to: /home/samantha/work/cogutils
in my case.  That is the parent directory.  So I went there and did a make and sudo make install.  Still no CogUtils which other parts of system complain about.  This is on ubuntu 17.01.

**Comment by sjatkins** [comment]
The following is what I see when I do the cmake.  Note that it shows missing deps for binutils-dev when I in fact have it and this libiberty-dev thing as well.  Problem in the dependency checks?

cmake ..
-- Build type: Release
-- BFD not found
-- Binutils-dev missing: No pretty stack-trace printing.
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   date_time
--   filesystem
--   program_options
--   regex
--   serialization
--   system
--   thread
--   chrono
--   atomic
-- Boost version 106200 found.
-- IBERTY not found
-- Libiberty-dev missing: No pretty stack-trace printing.

The following components will be built:
-----------------------------------------------
   Doxygen     - Code documentation.
   Unit tests  - Unit tests.
   Util        - General utility library.

The following components WILL NOT be built:
-----------------------------------------------
   StackPrint  - Pretty printing of stack traces.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/samantha/work/cogutils

**Comment by linas** [comment]
These instructions are correct:
```
cd to project root dir
mkdir build
cd build
cmake ..
make
```
The missing  libiberty thing can be ignored, for now: its a hassle to debug, and its not that important.

This message is bizzarre:
```
Build files have been written to: /home/samantha/work/cogutils
```
it really really should have been build.  Triple check you are in the build directory, delete everything, and try again. 

p.s. welcome to opencog, let the mailing list know what you hope to do, as I'm worried that as an old-timer to AGI but new to opencog means you'll be stumped/irritated by lots of things.

**Comment by sjatkins** [comment]
Thanks.  I did check it and retry a few times. Still seems to be happening.  
Mainly I just want to see the state of the art and perhaps roll up my sleeves to dive into a few places like the atomspace.    I need to refresh my *ugh* c++ skills for some of that though.

**Comment by linas** [comment]
Hi Samantha,
1) the error as described "can't happen"; so there is something deeper and more subtle going on. The error as described, does not make sense.
2) debugging it will not require C++ skills, but cmake skills. You'll have to dive into the plumbing of cmake to figure out why it got the install paths incorrect.

Thanks for calling opencog "state of the art", but in practice, it won't magically do anything interesting after compiling it.  Its more like a box of tinker toys: after a lot of work, you might be able to assemble some contraption that does something interesting. Right now, lots of assembly is required, and the resulting contraptions can be either awesome or underwhelming, depending on your point of view.

@mhatta is creating a set of debian packages for opencog; it might be easiest for yo to install those, and go from there.

**Comment by linas** [comment]
Closing, I don't see anything described here that is "fixable" at this point.
